### ISSUE TITLE
Nakshatra Windows binaries - WB/UCI compatibility

### ISSUE THREAD

**Issue by yellow-panther** [goutham/nakshatra#1]
Hello goutham,

is your engine compatible with the free available chess protocols **WinBoard (a.k.a. CECP) and UCI** (abreviation of Universal Chess Interface).Hundreds of chess programs (freeware/shareware) support both or at least one of these connections.

http://home.hccnet.nl/h.g.muller/engine-intf.html

http://hgm.nubati.net/CECP.html

http://www.shredderchess.com/download.html

http://download.shredderchess.com/div/uci.zip

Can your application be used for Windows operation systems (e.g. v7 or 10) too and do you have plans to create Winodws binaries (executable files)?

**Comment by goutham** [comment]
Hi,

Engine is compatible with CECP (it uses Xboard to connect to FICS). I've only ever run with Xboard. I've also never tried to build a windows binary and have no plans of doing so (though wouldn't mind someone else looking into this). There will certainly be some tweaks needed to run on Windows.

Thanks!
